"""The database structure has been changed. Added the mcc_codes table

Revision ID: 52498feaab3f
Revises: 723bcc1137fe
Create Date: 2025-04-06 19:45:44.663476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52498feaab3f'
down_revision: Union[str, None] = '723bcc1137fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcc_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_cashback_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_cashback_category_id'], ['cashback_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'cashback_category_with_bank', 'mcc_codes', ['mcc_code'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cashback_category_with_bank', type_='foreignkey')
    op.drop_table('mcc_codes')
    # ### end Alembic commands ###
